# -*- coding: utf-8 -*-
"""补充翻译：将用户可见但词典缺失/占位的文本翻译为简体中文，合并进 zh-CN.json"""
import json
import os

ROOT = r"D:\CodeProjects\DalamudPlugins\Demo\AutoRetainer"
DICT = os.path.join(ROOT, "tools", "zh-CN.json")

EXTRA = {
    # ---- About 页 ----
    "Published and developed with ": "由 Puni.sh 与 NightmareXIV 用 ",
    " by Puni.sh and NightmareXIV": " 制作并发布",
    "Join our Discord community for project announcements, updates, and support.": "加入我们的 Discord 社区，获取项目公告、更新与支持。",
    "Repository": "仓库",
    "Link copied to clipboard": "链接已复制到剪贴板",
    "Source Code": "源代码",
    "Donate to Puni.sh platform": "赞助 Puni.sh 平台",
    # ---- 远征/雇员页 ----
    "Add": "添加",
    "Build (1)": "建造 (1)",
    "Build (2)": "建造 (2)",
    "Build (3)": "建造 (3)",
    "Build (4)": "建造 (4)",
    "Level (1)": "等级 (1)",
    "Level (2)": "等级 (2)",
    "Level (3)": "等级 (3)",
    "Level (4)": "等级 (4)",
    "Route (1)": "航线 (1)",
    "Route (2)": "航线 (2)",
    "Route (3)": "航线 (3)",
    "Route (4)": "航线 (4)",
    "NOT": "非",
    "Affected {} submarines": "受影响 {} 艘潜水艇",
    "Affected {} characters": "受影响 {} 个角色",
    "Affected {} retainers": "受影响 {} 名雇员",
    "Changed {} retainers": "已更改 {} 名雇员",
    "Different setup for first Submersible###firstSubDifferent{}": "第一艘潜水艇的不同设置###firstSubDifferent{}",
    "Delete##{}": "删除##{}",
    # ---- 专家页 ----
    "Allow operating on retainers without a job": "允许操作没有职业的雇员",
    # ---- 调试 ----
    "Start": "开始",
    "Exit": "退出",
    "Selected": "已选择",
    "Step on": "步骤开启",
    "Step off": "步骤关闭",
    "Step": "步骤",
    "type": "类型",
    "Slot": "栏位",
    "Sell": "出售",
    "Enqueue if present": "存在则入队",
    "Interact with target": "与目标互动",
    "Vendor list": "商人列表",
    "Move stuck detection": "移动卡死检测",
    "Retainer item stats": "雇员物品属性",
    "Test Haseltweaks": "测试 HaselTweaks",
    "Write config via external process": "通过外部进程写入配置",
    "Housing": "房屋",
    "Simulate login": "模拟登录",
    "Install callback hook": "安装回调钩子",
    "Disable callback hook": "禁用回调钩子",
    "Log opcodes": "记录操作码",
    "Test entrust dup": "测试重复存放",
    "Chill frames lock": "解除帧率锁定",
    "Unlock frames lock": "启用帧率锁定",
    "Level array:": "等级数组:",
    "Regenerate censor seed": "重新生成屏蔽种子",
    "Task debug": "任务调试",
    "Fire": "触发",
    "Sorted data": "已排序数据",
    "Enqueue HET": "入队 HET",
    "Enqueue workshop": "入队工坊",
    "Fail": "失败",
    "Tasks": "任务",
    "Don't logout": "不登出",
    "Force mismatch": "强制不匹配",
    "Simulate nothing left": "模拟无剩余",
    "Simulate autostart": "模拟自动启动",
    "Delete was loaded data": "删除已加载数据",
    "Enter house": "进入房屋",
    "Estate territories": "房屋领地",
    "Bypass sanctuary check": "跳过安全区检查",
    "msg no title": "消息（无标题）",
    "play sound": "播放声音",
    "stop sound": "停止声音",
    "Run task": "运行任务",
    "Retainer name": "雇员名称",
    "Select retainer by name": "按名称选择雇员",
    "AtkStage get focus": "AtkStage 获取焦点",
    "AtkStage clear focus": "AtkStage 清除焦点",
    "Try retrieve current retainer name": "尝试获取当前雇员名称",
    "Try close": "尝试关闭",
    "test bank": "测试银行",
    "Venture id": "委托 ID",
    "Venture name": "委托名称",
    "Clear Venture list": "清空委托列表",
    "SelectSpecificVenture Name": "按名称选择指定委托",
    "Select": "选择",
    "Interact with nearest panel": "与最近的界面互动",
    "Print best exp": "打印最佳经验",
    "subject name": "主题名称",
    "Test task manager": "测试任务管理器",
    "Test redeploy airship": "测试重新部署飞空艇",
    "Pick": "选择",
    "utils": "工具",
    "control": "控制",
    "Data Not Ready": "数据未就绪",
    "Inventory slots: ": "背包栏位: ",
    "Ventures: ": "委托: ",
    "Deliver items": "交付物品",
    "Expert items": "专家物品",
    "API Test": "API 测试",
    "Suppress = true": "抑制 = 开启",
    "Suppress = false": "抑制 = 关闭",
    "Inventories": "背包",
    "Shop Sell test": "商店出售测试",
    "Points: {}": "点数: {}",
    "WorkshopUI planner button": "工坊界面规划按钮",
    "Public debug": "公开调试",
    "Generate random numbers 1/100": "生成随机数 1/100",
    "Generate random numbers 1/500": "生成随机数 1/500",
    "Generate random numbers 1/5000": "生成随机数 1/5000",
    # ---- 通知/提示 ----
    "Logout while waiting to return to home; expecting DC travel. Aborting and waiting for relogging.": "等待返回房屋时登出；预期跨数据中心传送。已中止并等待重新登录。",
    "Failed to find suitable house": "找不到合适的房屋",
    "AutoRetainer is busy or player is occupied.": "AutoRetainer 正忙或玩家处于忙碌状态。",
    "... {} more ...": "... 还有 {} 个 ...",
    "{} - {} Configuration  ##conf": "{} - {} 配置  ##conf",
    "Used by {} characters in total": "共有 {} 个角色使用",
    "You are required to enable this function globally as well in order for it to work.": "你必须同时在全局设置中启用此功能，它才能生效。",
    "This plan is used by {}.": "该方案已被 {} 使用。",
    "This plan is used by {} submersibles of your other characters.": "该方案被你其他角色的 {} 艘潜水艇使用。",
    "This plan is used by {} and {} more submersibles on other characters.": "该方案被你其他角色的 {} 艘及另外 {} 艘潜水艇使用。",
    "Could not import plan: {}": "无法导入方案: {}",
    "Using custom FFXIVClientStructs": "使用自定义 FFXIVClientStructs",
    "Could not find target character": "找不到目标角色",
    "Failed to enter workshop": "无法进入工房",
    "No valid housing NPC or retainer bell were found, or AutoRetainer is busy, or sale function is disabled": "未找到有效的房屋 NPC 或雇员铃，或 AutoRetainer 正忙，或出售功能已禁用",
    "Glamour Log plugin is required for this function.": "此功能需要 Glamour Log 插件。",
    "Timer can't be less than 10 seconds": "计时器不能少于 10 秒",
    "External addition to soft vendor list: {}": "外部添加到软商人列表: {}",
    "External removal from soft vendor list: {}": "外部从软商人列表移除: {}",
    "Reset completed": "重置完成",
    "Open bell action cancelled": "打开铃铛的操作已取消",
    "Lifestream plugin is not installed or not enabled. You have to install and enable it in order for {} to work. Click here if you would like to open an instruction on how to do so.": "Lifestream 插件未安装或未启用。你必须安装并启用它，{} 才能正常工作。如需查看操作说明，请点击此处。",
    "Requested discard of slot {}[{}], item {}, is protected, can not discard": "请求丢弃栏位 {}[{}] 中的物品 {} 受保护，无法丢弃",
    "Would discard {} {} x{}, {}[{}]": "将丢弃 {} {} x{}，{}[{}]",
    "Requested discard of slot {}[{}], expected item {}, contained {}, can not discard": "请求丢弃栏位 {}[{}]，预期物品 {}，实际为 {}，无法丢弃",
    "The venture list is too large to show preview.": "委托列表过大，无法显示预览。",
    "Progress: {}/{}": "进度: {}/{}",
    "Hold both CTRL+SHIFT while clicking to remove protection from item": "按住 CTRL+SHIFT 点击可从物品上移除保护",
    "Item {} removed from Quick Venture sell list": "物品 {} 已从快速探险出售列表移除",
    "Item {} added to Quick Venture sell list": "物品 {} 已添加到快速探险出售列表",
    "Item {} removed from Unconditional sell list": "物品 {} 已从无条件出售列表移除",
    "Item {} added to Unconditional sell list": "物品 {} 已添加到无条件出售列表",
    "Item {} removed from Discard list": "物品 {} 已从丢弃列表移除",
    "Item {} added to Discard list": "物品 {} 已添加到丢弃列表",
    "{} added to protection list": "{} 已添加到保护列表",
    "Could not acquire lock.": "无法获取锁。",
    "Requested inventory slot {}({}) had no item in it to sell.": "请求出售的背包栏位 {}({}) 中没有物品。",
    "Inventory {} is null": "背包 {} 为空",
    "Item {} is protected and won't be sold.": "物品 {} 受保护，不会被出售。",
    "Slot contains different item {}x{}, should be {}": "栏位包含不同的物品 {}x{}，应为 {}",
    "Could not find retainer inventory": "找不到雇员背包",
    "AgentRetainer is not active": "AgentRetainer 未激活",
    "> IMDry > Would sell slot {}": "> IMDry > 将出售栏位 {}",
    "[Bailout] Closing stuck SelectString window": "[Bailout] 关闭卡住的选项窗口",
    "[Bailout] Backing out of CharaSelect": "[Bailout] 退出角色选择",
    "Unsafe option removed: character {} - {}": "已移除不安全选项: 角色 {} - {}",
    "Don't use GetGCInfo IPC method, it is now obsolete.": "请勿使用 GetGCInfo IPC 方法，它已过时。",
    "[ARERRCMM] Character mismatch, expected {}, but logged in on {}. Please report this to developer unless you have manually interfered with login process": "[ARERRCMM] 角色不匹配，预期 {}，但登录的是 {}。除非你手动干预了登录过程，否则请向开发者报告此问题",
    "Multi mode disabled as it have detected duplicate login.": "多角色模式已禁用，因为检测到重复登录。",
    "Could not shutdown the game normally, forcing exit": "无法正常关闭游戏，强制退出",
    "Error while automatically logging in: {}": "自动登录时出错: {}",
    "Too many errors, current character is excluded.": "错误过多，当前角色已被排除。",
    "Fatal error. Please report this with logs.": "致命错误。请连同日志报告此问题。",
    "Due to absence of retainer bell and failure to find workshop, character is excluded from processing retainers": "由于没有雇员铃且无法找到工房，该角色已被排除在雇员处理之外",
    "Preferred character has been reset": "首选角色已重置",
    "Error during auto login: {}": "自动登录期间出错: {}",
    "[Voyage] You are out of repair components!": "[远征] 你的修理配件用完了！",
    "No operation was requested by user": "用户未请求任何操作",
    "Warning!\nDeployables were not enabled as there are nothing to process yet": "警告！\n远征探险未启用，因为还没有任何可处理的内容",
    "Invalid plan selected (Points.Count={})": "选择了无效的方案（点数数量={}）",
    "Item id for airship component was 0 ({})": "飞空艇配件的物品 ID 为 0（{}）",
    "Critical error occurred during path optimization: {}": "航线优化期间发生严重错误: {}",
    "Due to failure to find workshop, character is excluded from processing deployables": "由于无法找到工房，该角色已被排除在远征探险处理之外",
    "Invalid map index specified (specified {}, max {})": "指定了无效的地图索引（指定 {}，最大 {}）",
    "[Voyage] You are out of fuel!": "[远征] 你的燃料用完了！",
    "Error calculating best path": "计算最佳航线时出错",
    "Calculating optimized path. Please wait.": "正在计算优化航线，请稍候。",
    "This can take several minutes.": "这可能需要几分钟。",
    "Hide this overlay": "隐藏此覆盖层",
    "Your inventory is full": "你的背包已满",
    "Enforcing {} ": "强制执行 {} ",
    "Can not find venture id {} [{}] in list {}": "在列表 {} 中找不到委托 ID {} [{}]",
    "Not employed by a Grand Company": "未加入大国防联军",
    "Can not enqueue GC delivery as it is disabled for current character": "无法入队军需交付，因为当前角色已禁用此功能",
    "Lifestream is busy": "Lifestream 正忙",
    "AutoRetainer is busy": "AutoRetainer 正忙",
    "Desynthing {} [Container={},Slot={}]": "分解 {} [容器={}，栏位={}]",
    "Upon returning home, apartment not found. Aborting and retrying.": "返回房屋时未找到公寓，正在中止并重试。",
    "Free company house is registered in Lifestream and path is set. You will be teleported to Free company house for resending Deployables. If enabled, you will be teleported to Free company house for resending retainers as well.\nAddress: {}, ward {}, plot {}": "已在 Lifestream 中登记部队房屋并设置路径。将传送你到部队房屋以重新派遣远征探险。如已启用，也会传送你到部队房屋以重新派遣雇员。\n地址: {}，区 {}，地块 {}",
    "Private house is registered in Lifestream and path is set. You will be teleported to Private house for resending Retainers.\nAddress: {}, ward {}, plot {}": "已在 Lifestream 中登记私人房屋并设置路径。将传送你到私人房屋以重新派遣雇员。\n地址: {}，区 {}，地块 {}",
    "Unlimited": "无限",
    "Enable {}": "启用 {}",
    "Abort {} tasks": "中止 {} 个任务",
    "Service Account {}": "服务账号 {}",
    "Inn cutscene skip module is set to {}. Inn cutscene will be skipped by AutoRetainer.": "旅馆过场跳过模块已设置为 {}。AutoRetainer 将跳过旅馆过场动画。",
    "Multi Mode expert delivery free inventory slot trigger value is set to {} while submersible module is enabled. It is recommended to set it to at least 50 to avoid inventory overflow issues.": "在潜水艇模块启用的情况下，多角色模式专家交付的空闲背包栏位触发值被设置为 {}。建议至少设置为 50，以避免背包溢出问题。",
    "Some of your multi-mode enabled characters have {} retainers enabled, and Multi Mode expert delivery free inventory slot trigger value is set to {}. It is strongly recommended that you set it to at least {} (5 slots per retainer).": "你的一些多角色模式角色启用了 {} 名雇员，而多角色模式专家交付的空闲背包栏位触发值被设置为 {}。强烈建议你至少设置为 {}（每名雇员 5 个栏位）。",
    "Character {} has duplicate submersible names. Submersible names must be unique.": "角色 {} 有重复的潜水艇名称。潜水艇名称必须唯一。",
    "Submarine unlock plan {} is set as enforced and will override any submarine settings if there is anything to unlock.": "潜水艇解锁方案 {} 被设置为强制生效，如果有任何可解锁内容，它将覆盖所有潜水艇设置。",
    "Submarine unlock plan {} is set to deploy on single point in Deep sea site, and it will ignore unlock behavior that is manually set.": "潜水艇解锁方案 {} 被设置为在深海点部署单点，并将忽略手动设置的解锁行为。",
    "Your MultiMode type is set to {}. This will limit functions that AutoRetainer will perform.": "你的多角色模式类型被设置为 {}。这将限制 AutoRetainer 执行的功能。",
    'Expert setting "{}" differs from default': '专家设置 "{}" 与默认值不同',
    'Default is "{}", current is "{}".': '默认值为 "{}"，当前为 "{}"。',
    "You can construct new submersible ({}/{})": "你可以建造新的潜水艇（{}/{}）",
    "Repair {} submarine's broken components": "修理 {} 艘潜水艇的损坏配件",
    "Currently executing: {}": "当前正在执行: {}",
    "Index override: {}": "索引覆盖: {}",
    "Moved data from {} to {}": "已将数据从 {} 移动到 {}",
    'Entrust plan "{}" is active.': '存放计划 "{}" 已激活。',
    "Number of columns": "列数",
    "Overlay height, %": "覆盖层高度，%",
    "Added {} to entrust plan {}": "已将 {} 添加到存放计划 {}",
    "Removed {} from entrust plan {}": "已将 {} 从存放计划 {} 移除",
    "Selected {} items, among which {} already present in list###counter": "已选择 {} 个物品，其中 {} 个已在列表中###counter",
    "Exclude {}##item": "排除 {}##item",
    "Exclude {}": "排除 {}",
    "Added {} to Quick Venture Sell List": "已将 {} 添加到快速探险出售列表",
    "Added {} to Unconditional Sell List": "已将 {} 添加到无条件出售列表",
    "Added {} to Discard List": "已将 {} 添加到丢弃列表",
    "Removed {} from Quick Venture Sell List": "已将 {} 从快速探险出售列表移除",
    "Removed {} from Unconditional Sell List": "已将 {} 从无条件出售列表移除",
    "Removed {} from Discard List": "已将 {} 从丢弃列表移除",
    "Removed {} from Desynthesis List": "已将 {} 从分解列表移除",
    "Deliver eligible items into Armoire when in Multi Mode": "多角色模式下将符合条件的物品放入置衣柜",
    "Items that are not in Armoire will be delivered there. Eligible items also will be excluded from being discarded, desynthesed, entrusted to retainers or delivered into grand company (only while you are running multi mode). This will trigger before Multi Mode Expert Delivery.": "不在置衣柜中的物品将被放入其中。符合条件的物品也将被排除在丢弃、分解、存放至雇员或上交大国防联军之外（仅在多角色模式运行时）。此操作将在多角色模式专家交付之前触发。",
    "Deliver eligible items into glamour dresser while in Multi Mode (requires Glamour log plugin)": "多角色模式下将符合条件的物品放入投影柜（需要 Glamour Log 插件）",
    "Allow this character to use FC buffs": "允许此角色使用部队增益",
    "Allow this character to use priority seal allowance": "允许此角色使用优先军票配额",
    "Delete##bl{}": "删除##bl{}",
    "Delay, seconds": "延迟（秒）",
    "Delay": "延迟",
    "Set appropriate delay to let plugins fully load before logging in and to allow yourself some time to cancel login if needed": "设置适当的延迟，让插件在登录前完全加载，并留出时间以便在需要时取消登录",
    "When enabled, AutoRetainer will wait for all deployables to return before logging into the character. If you're already logged in for another reason, it will still resend completed submarines\u2014unless the global setting ": "启用后，AutoRetainer 将等待所有远征探险返回后才登录该角色。如果你因其他原因已登录，它仍会重新派遣已完成的潜水艇——除非全局设置 ",
    " is also turned on.": " 也已开启。",
    "Changes the behavior of ": "改变 ",
    " (both global and per-character) so that AutoRetainer no longer resends individual submarines while already logged in. Instead, it will wait until all submarines have returned before taking action.": "（全局和按角色）的行为，使 AutoRetainer 在已登录时不再单独重新派遣潜水艇。相反，它会等待所有潜水艇返回后再采取行动。",
    "If waiting for other deployables to return would exceed this number of minutes, AutoRetainer will ignore both the ": "如果等待其他远征探险返回的时间将超过此分钟数，AutoRetainer 将忽略 ",
    " and ": " 和 ",
    " settings.": " 设置。",
    "Check frequency, hours": "检查频率（小时）",
    "Enable on {}": "在 {} 上启用",
    "{} items left": "剩余 {} 个物品",
    "No entrust plan found for retainer {}": "未找到雇员 {} 的存放计划",
    "No items in inventory to entrust": "背包中没有可存放的物品",
    "Last updated {}. Ctrl + click to reset": "最后更新于 {}。Ctrl + 点击可重置",
    "Last updated {}": "最后更新于 {}",
    "        Free Company {}: {}": "        部队 {}: {}",
    "Data center total ({}): {}": "数据中心总计（{}）: {}",
    "Overall total: {}": "总计: {}",
    "Error: {}": "错误: {}",
    "{}{} {} | Gathering: {} ({}) | Perception: {} ({})": "{}{} {} | 采集力: {} ({}) | 鉴别力: {} ({})",
    "{}{} {} | Item Level: {} ({})": "{}{} {} | 物品等级: {} ({})",
    "To planner##{}": "前往规划器##{}",
    "Check price##{}": "查看价格##{}",
    "Gather##{}": "采集##{}",
    "Plan {} saved!": "方案 {} 已保存！",
    "{}    Quick Exploration": "{}    快速探险",
    "TOTAL": "总计",
    "Important: when activated, your multi mode will be set to do deployables only, no retainers.": "重要提示：启用后，多角色模式将仅处理远征探险，不处理雇员。",
    "Maximum time to wait for sub return, minutes": "等待潜水艇返回的最长时间（分钟）",
    "Run a specific entrust plan": "运行指定的存放计划",
    "Reverse run a specific entrust plan (withdraw items according to entrust plan from retainers)": "反向运行指定的存放计划（根据存放计划从雇员处取回物品）",
    "Left click - relog to this character\nRight click - copy relog command into clipboard": "左键 - 重新登录到此角色\n右键 - 将重新登录命令复制到剪贴板",
}

with open(DICT, encoding="utf-8-sig") as f:
    data = json.load(f)

added = 0
updated = 0
for k, v in EXTRA.items():
    if k in data:
        if data[k] == k or data[k] == "":
            data[k] = v
            updated += 1
        else:
            print(f"跳过(已有翻译): {k[:60]!r} => {data[k][:40]!r}")
    else:
        data[k] = v
        added += 1

with open(DICT, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print(f"新增: {added}, 更新占位: {updated}, 总条目: {len(data)}")
